2 - Jf rawdataprocess fmt
slsdetectorgroup/slsDetectorPackage pull request #725
Opened 2023-04-27 10:14 UTC by vhinger182

Implement filename parsing using fmt::format + bug fixes

2023-04-27 14:27 UTC, erikfrojdh requested changes
Could you fix the const&? If the functions are to be used in other files we could break out the functions and add also a small test... but that's for next time.

2023-04-27 15:01 UTC, vhinger182 commented on slsDetectorCalibration/jungfrauExecutables/jungfrauRawDataProcess.cpp
> +std::string getRootString( const std::string filepath ) {
True! I'll change it.
Just to be sure about the workflow: Do I simply make a new commit with the changes on my local branch and push it? Or can I do it differently?

2023-04-27 15:12 UTC, erikfrojdh commented on slsDetectorCalibration/jungfrauExecutables/jungfrauRawDataProcess.cpp
> +std::string getRootString( const std::string filepath ) {
Easiest is to make a commit to jf_rawdataprocess_fmt on your machine and push it to github. That will automatically update the PR

2023-04-27 15:37 UTC, vhinger182 commented on slsDetectorCalibration/jungfrauExecutables/jungfrauRawDataProcess.cpp
> +std::string createFileName( const std::string dir, std::string fprefix="run", std::string fsuffix="", std::string fext="raw", int aindex=0, int mindex=0, int findex=0, int outfilecounter=-1 ) {
The ones that have a default value I cannot make const& right?

2023-04-28 13:53 UTC, vhinger182 commented on slsDetectorCalibration/jungfrauExecutables/jungfrauRawDataProcess.cpp
> +std::string createFileName( const std::string dir, std::string fprefix="run", std::string fsuffix="", std::string fext="raw", int aindex=0, int mindex=0, int findex=0, int outfilecounter=-1 ) {
Ok, fixed it! :)

2023-05-03 06:43 UTC, erikfrojdh approved these changes

2023-05-03 06:43 UTC, merged